# Generated by Django 5.1.6 on 2025-03-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_auto_reply_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailinquiry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_auto_reply_project.inquiryuser",
            ),
        ),
        migrations.AlterField(
            model_name="inquiryquestion",
            name="email_inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="email_auto_reply_project.emailinquiry",
            ),
        ),
    ]
